// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_57CM8CdQwFySViN3moAFiV1cZGO6_LA',
    appId: '1:921972486188:web:3b65162c0aeb65f19fa189',
    messagingSenderId: '921972486188',
    projectId: 'greenlife-e832e',
    authDomain: 'greenlife-e832e.firebaseapp.com',
    storageBucket: 'greenlife-e832e.firebasestorage.app',
    measurementId: 'G-6YDRJSSG3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjqNpfu-vIpQ1fjg-XV3cBPw1pSSLYwbM',
    appId: '1:921972486188:android:f89460f428eb0ecc9fa189',
    messagingSenderId: '921972486188',
    projectId: 'greenlife-e832e',
    storageBucket: 'greenlife-e832e.firebasestorage.app',
  );
}
